// app/layout.tsx
import type { Metadata } from "next";
import { getInitialThemeScript } from '@/lib/setInitialTheme'
import "./globals.css";
import Providers from './providers'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="relative min-h-screen text-text-light dark:text-text-dark bg-dom-light dark:bg-dom-dark" >
        <script
          dangerouslySetInnerHTML={{
            __html: getInitialThemeScript(),
          }}
        />
        <div className="fixed inset-0 -z-10 opacity-20 dark:opacity-10 bg-gradient-to-b  from-background-lightContrast1 to-primary-light dark:from-background-darkGrad dark:to-background-dark"/>

        {/* ✅ Proveedor de sesión dentro de un Client Component */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
